export const products = [
  {
    "id": "4569",
    "name": "L'ÉCLAT 2021 - DOMAINE DE JOŸ",
    "type": "Vin blanc",
    "year": "2021",
    "alcool": "11,5 % vol",
    "volume": "0,75 L",
    "descriptionShort": "L'Éclat du domaine de Joÿ est un vin de plaisir immédiat à déguster sur sa jeunesse, pour le plaisir de la fraîcheur et du fruité !",
    "descriptionLong": "La cuvée l'Éclat offre une robe pâle aux reflets verts. Le nez frais et fruité présente des notes d'agrumes (pamplemousse, citron) et de fruits exotiques (litchi). En bouche, le vin est frais, rond et se termine sur des notes délicieusement fruitées. L'Eclat du domaine de Joÿ est un vin de plaisir à boire jeune, entre amis, à l'apéritif, sur des fruits de mer et crustacés, des poissons grillés, du Comté, des fromages de chèvres frais !",
    "imageFileName": "l-eclat-2021-domaine-de-joy.png",
    "imageAlt": "Bouteille de vin L'éclat 2021 - Domaine de Joÿ",
    "price": "7€60"
  },
  {
    "id": "5264",
    "name": "CLASSIC 2021 - DOMAINE TARIQUET",
    "type": "Vin blanc",
    "year": "2021",
    "alcool": "10,5 % vol",
    "volume": "0,75 L",
    "descriptionShort": "Le domaine Tariquet a réussi à proposer un vin de tous les instants ! A l'apéritif, sur un repas, en famille, entre amis...",
    "descriptionLong": "Chaque gorgée dégustée est une véritable explosion de fruits (d'agrumes), accompagnée d'une agréable fraîcheur qui fera appel à une nouvelle gorgée. Le conseil de nos sommeliers : avoir toujours une bouteille au frais... au cas où !",
    "imageFileName": "classic-2021-domaine-tariquet.png",
    "imageAlt": "Bouteille de vin Tariquet Classic 2021",
    "price": "7€65"
  },
  {
    "id": "8745",
    "name": "HARMONIE DE GASCOGNE BLANC 2022 - DOMAINE PELLEHAUT",
    "type": "Vin blanc",
    "year": "2022",
    "alcool": "11 % vol",
    "volume": "0,75 L",
    "descriptionShort": "Complexe et plein d'expression, cet Harmonie de Gascogne blanc est délicieusement bon!",
    "descriptionLong": "Dans une robe limpide et brillante, le vin offre un nez plein de senteurs sur des notes de fleurs, de fruits mûrs et de fruits confits. L'attaque est franche pour une bouche souple et suave, très équilibrée et persistante. Ce millésime révèle une intensité et une concentration sans égale!",
    "imageFileName": "harmonie-de-gascogne-blanc-2022-domaine-pellehaut.png",
    "imageAlt": "Bouteille de vin Harmonie de Gascogne Blanc 2022",
    "price": "9€20"
  },
  {
    "id": "1564",
    "name": "MONTAGNE NOIRE 2021 - CHATEAU AUZIAS",
    "type": "Vin rouge",
    "year": "2021",
    "alcool": "13,5 % vol",
    "volume": "0,75 L",
    "descriptionShort": "Pour les amateurs de valeurs sûres : ce rouge du Languedoc multi-récompensé à petit prix est fait pour vous !",
    "descriptionLong": "Des amis qui débarquent à l’improviste ? Une envie de s’ouvrir un bouteille de rouge, comme ça, juste pour le plaisir d’accompagner un morceau de fromage et un peu de charcuterie ? Avec Montagne Noire du Château d’Auzias on a tout bon ! Ses notes de fruits noirs et d’épices délicates agrémentent à merveille ce petit vin rouge du Languedoc au rapport qualité-prix-plaisir imbattable ! Foncez !",
    "imageFileName": "montagne-noire-2021-chateau-auzias.png",
    "imageAlt": "Bouteille de vin Montagne Noire 2021 - Chateau Auzias",
    "price": "6€90"
  },
  {
    "id": "8749",
    "name": "UBY BYO ROSE N°26 2021 - DOMAINE UBY",
    "type": "Vin rosé",
    "year": "2021",
    "alcool": "11,5 % vol",
    "volume": "0,75 L",
    "descriptionShort": "Découvrez la gamme Byo du domaine Uby à travers ce délicieux rosé !!",
    "descriptionLong": "L'intégralité du vignoble d'Uby est certifié Viticulture Raisonnée Contrôlée depuis 10 ans et les vignes issues de l'agriculture biologique représentent 70 hectares du domaine. Cette cuvée rosée de la gamme Byo est un vrai régal... Avec des notes de framboise, de groseilles, le vin dégage une grande fraîcheur avec une bouche grasse et ample sur une délicieuse finale de fruits frais... Une pure gourmandise !",
    "imageFileName": "uby-byo-rose-n26-2021-domaine-uby.png",
    "imageAlt": "Bouteille de vin Uby Byo Rosé N°26 2021 - Domaine Uby",
    "price": "7€90"
  },
];
